/* Edge-IQ Basketball Model V1
   NBA/NBL: transparent, recency-weighted team-strength model.
   Uses historical final scores from ESPN's public scoreboard feed.
   Produces moneyline, spread and total probabilities when market lines are supplied.
   This is a research/paper model until walk-forward validation gates are passed.
*/
const clamp=(x,a=.02,b=.98)=>Math.max(a,Math.min(b,x));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const key=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const erf=x=>{const s=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a),y=1-((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a);return s*y};
const normalCdf=(x,mu=0,sd=1)=>.5*(1+erf((x-mu)/(sd*Math.sqrt(2))));
function parseGame(g){const home=g.home_team||g.home?.name||g.homeTeam||g.competitions?.[0]?.competitors?.find(x=>x.homeAway==='home')?.team?.displayName;const away=g.away_team||g.away?.name||g.awayTeam||g.competitions?.[0]?.competitors?.find(x=>x.homeAway==='away')?.team?.displayName;const hs=num(g.home_score??g.home_points??g.homeScore??g.competitions?.[0]?.competitors?.find(x=>x.homeAway==='home')?.score);const as=num(g.away_score??g.away_points??g.awayScore??g.competitions?.[0]?.competitors?.find(x=>x.homeAway==='away')?.score);if(!home||!away||hs==null||as==null)return null;return {home,away,hs,as,date:g.start_time||g.date||g.dateScheduled||g.competitions?.[0]?.date||''}}
function build(games,{initial=100,homeAdv=2.5,k=0.055,formGames=12,decay=.97}={}){const r=new Map(),s=new Map();const get=t=>r.get(t)||{off:initial,def:initial,n:0};const hist=t=>s.get(t)||[];const sorted=games.map(parseGame).filter(Boolean).sort((a,b)=>new Date(a.date)-new Date(b.date));for(const g of sorted){const h=key(g.home),a=key(g.away),H=get(h),A=get(a),hp=(H.off-A.def+homeAdv+100)/2,ap=(A.off-H.def+100)/2;const he=g.hs-hp,ae=g.as-ap;const damp=Math.min(1.5,Math.max(.55,Math.log1p(Math.abs(g.hs-g.as))/1.5));H.off+=k*damp*he;H.def-=k*damp*he;A.off+=k*damp*ae;A.def-=k*damp*ae;r.set(h,H);r.set(a,A);for(const [t,pts,opp] of [[h,g.hs,g.as],[a,g.as,g.hs]]){const arr=hist(t);arr.push({pts,opp});if(arr.length>formGames)arr.shift();s.set(t,arr)}}return {ratings:r,history:s,params:{initial,homeAdv,k,formGames,decay},gamesUsed:sorted.length}}
function predictOne(model,home,away){const h=key(home),a=key(away),H=model.ratings.get(h)||{off:100,def:100},A=model.ratings.get(a)||{off:100,def:100};const hs=model.history.get(h)||[],as=model.history.get(a)||[];const havg=hs.length?hs.reduce((x,g,i)=>x+g.pts*Math.pow(model.params.decay,hs.length-1-i),0)/hs.reduce((x,_,i)=>x+Math.pow(model.params.decay,hs.length-1-i),0):100;const aavg=as.length?as.reduce((x,g,i)=>x+g.pts*Math.pow(model.params.decay,as.length-1-i),0)/as.reduce((x,_,i)=>x+Math.pow(model.params.decay,as.length-1-i),0):100;const homeScore=clamp((H.off-A.def+model.params.homeAdv+100)/2*.55+havg*.45,75,150);const awayScore=clamp((A.off-H.def+100)/2*.55+aavg*.45,75,150);const margin=homeScore-awayScore,total=homeScore+awayScore;const sd=11.5;return {homeScore,awayScore,margin,total,winHome:clamp(normalCdf(0,margin,sd)),sd,gamesUsed:model.gamesUsed}}
function eventPredictions(model,e){const p=predictOne(model,e.home_team||e.home,e.away_team||e.away);return {event_id:e.event_id,source:'BASKETBALL_V1',gamesUsed:p.gamesUsed,homeProbability:p.winHome,awayProbability:1-p.winHome,expectedHomeScore:p.homeScore,expectedAwayScore:p.awayScore,expectedMargin:p.margin,expectedTotal:p.total,scoreSd:p.sd,features:['recency_weighted_team_strength','home_advantage','recent_scoring']}}
function marketProbability(pred,line,kind,side){const n=num(line);if(n==null)return null;if(kind==='spread'){const margin=side==='home'?pred.margin:-pred.margin;return clamp(normalCdf(-n,margin,pred.sd),.01,.99)}if(kind==='total'){const total=pred.total;return clamp(side==='over'?1-normalCdf(n,total,pred.sd):normalCdf(n,total,pred.sd),.01,.99)}return side==='home'?pred.homeProbability:pred.awayProbability}
function predict(model,events){return (events||[]).map(e=>eventPredictions(model,e))}
export {build,predict,predictOne,eventPredictions,marketProbability,key};
