/* Edge-IQ market scanner v3.1. Multi-sport model probabilities + strict baseline separation. */
(function(){
 const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};const key=v=>String(v??'').trim().toLowerCase();const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const clamp=(x,a=.01,b=.99)=>Math.max(a,Math.min(b,x));const erf=x=>{const s=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a),y=1-((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a);return s*y};const cdf=(x,mu,sd)=>.5*(1+erf((x-mu)/(sd*Math.sqrt(2))));
 const isWin=m=>/moneyline|match.?winner|winner|h2h|1x2|head.?to.?head/i.test(String(m||''));const isSpread=m=>/spread|handicap|run.?line|line/i.test(String(m||''))&&!/total/i.test(String(m||''));const isTotal=m=>/total|over.?under|ou/i.test(String(m||''));
 function modelProbFor(e,side,market,line){const p=e?.model_probabilities;if(isWin(market)&&p){const v=side==='home'?num(p.home):side==='away'?num(p.away):null;return v!=null&&v>0&&v<1?v:null}const x=e?.model_expected,ln=num(line);if(!x||ln==null)return null;if(isSpread(market)){const margin=num(x.margin??x.expectedMargin);const sd=Math.max(.5,num(x.marginSd??x.sd)??4);if(margin==null)return null;const m=side==='home'?margin:-margin;return clamp(cdf(-ln,m,sd),.01,.99)}if(isTotal(market)){const total=num(x.total??x.expectedTotal);const sd=Math.max(.5,num(x.totalSd??x.sd)??3.8);if(total==null)return null;return clamp(side==='over'?1-cdf(ln,total,sd):cdf(ln,total,sd),.01,.99)}return null}
 function flatten(data){const rows=[],baseFor=e=>({eventId:e.event_id,event:`${e.home_team||''} v ${e.away_team||''}`,start:e.start_time,league:e.league||'',sport:e.sport||'',home:e.home_team||e.home,away:e.away_team||e.away,modelSource:e.model_source||null,modelGamesUsed:e.model_games_used||null,modelDisagreement:e.model_disagreement??null,modelExpected:e.model_expected||null});for(const e of(data?.events||[])){const base=baseFor(e);for(const[marketKey,m]of Object.entries(e.lines||{})){for(const b of(m?.books||[]))for(const side of['home','away','draw','over','under']){const o=b?.[side];if(!o)continue;const odds=num(o.odds??o.decimal_odds);if(!(odds>1))continue;const line=o.line??o.points??o.total??m.line??null;rows.push({...base,market:marketKey,marketType:m.market_type||'',period:m.period_str||'',line,selection:o.selection_name||o.name||side,side,book:key(b.bookmaker||b.name||'unknown'),odds,modelProb:modelProbFor(e,side,marketKey,line)})}}}for(const e of(data?.events||[])){if(!Array.isArray(e.items))continue;const base=baseFor(e);for(const x of e.items){const odds=num(x.odds??x.decimal_odds);if(!(odds>1))continue;const market=x.market_key||x.bet_type||'market',line=x.line??x.points??x.total??null,side=x.side||'';rows.push({...base,market,marketType:x.market_type||'',period:x.period_str||'',line,selection:x.selection_name||x.selection||side,side,book:key(x.bookmaker||x.bookmaker_name||'unknown'),odds,modelProb:modelProbFor(e,side,market,line)})}}return rows}
 function addBookMetrics(rows){const groups=new Map();for(const r of rows){const k=[r.eventId||r.event,r.market,r.period,r.line??''].map(key).join('|'),bk=k+'|'+r.book;if(!groups.has(bk))groups.set(bk,[]);groups.get(bk).push(r)}for(const g of groups.values()){const inv=g.reduce((s,r)=>s+1/r.odds,0);g.forEach(r=>{r.rawProb=1/r.odds;r.noVigProb=inv>0?r.rawProb/inv:null;r.bookMargin=inv-1})}}
 function median(values){const a=values.filter(v=>v!=null).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
 function scan(data){const rows=flatten(data);addBookMetrics(rows);const groups=new Map();for(const r of rows){const k=[r.eventId||r.event,r.market,r.period,r.line??''].map(key).join('|');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}const opportunities=[];for(const g of groups.values()){const selections=new Map();for(const r of g){if(!selections.has(key(r.selection)))selections.set(key(r.selection),[]);selections.get(key(r.selection)).push(r)}for(const prices of selections.values()){const valid=prices.filter(r=>r.noVigProb!=null);if(!valid.length)continue;const probs=valid.map(r=>r.noVigProb),consensusProb=median(probs),meanProb=probs.reduce((a,b)=>a+b,0)/probs.length,dispersion=Math.sqrt(probs.reduce((s,p)=>s+(p-meanProb)**2,0)/probs.length),best=prices.reduce((a,b)=>b.odds>a.odds?b:a),fair=1/consensusProb,books=prices.length,coverage=Math.min(1,books/5),agreement=Math.max(0,1-dispersion*500),confidence=Math.round(100*Math.max(0,Math.min(1,.55*coverage+.45*agreement))),modelProb=best.modelProb,modelEv=modelProb!=null?modelProb*best.odds-1:null;opportunities.push({...best,books,consensusProb,meanProb,consensusEv:consensusProb*best.odds-1,ev:consensusProb*best.odds-1,modelEv,modelFair:modelProb!=null?1/modelProb:null,fair,dispersion,confidence,edgeQuality:confidence/100,bestVsMedian:best.odds/fair-1,modelSource:modelProb!=null?(best.modelSource||'MODEL'):'BASELINE',signal:modelProb!=null?'MODEL':'VERIFY',modelDisagreement:best.modelDisagreement,modelExpected:best.modelExpected,prices})}}opportunities.sort((a,b)=>(b.modelEv??-Infinity)-(a.modelEv??-Infinity)||b.confidence-a.confidence||b.books-a.books);return{rows,opportunities,positive:opportunities.filter(x=>x.modelEv>0),modelMeta:data?.model_meta||null}}
 window.EdgeIQScanner={scan,flatten,esc,median};
})();
