/* Edge-IQ MLB Model V1
   Transparent, recency-weighted run model for MLB moneyline, run line and totals.
   Research/paper model until walk-forward validation gates are passed.
*/
const clamp=(x,a=.02,b=.98)=>Math.max(a,Math.min(b,x));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const key=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const erf=x=>{const s=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a),y=1-((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a);return s*y};
const normalCdf=(x,mu=0,sd=1)=>.5*(1+erf((x-mu)/(sd*Math.sqrt(2))));
function parseGame(g){const comps=g.competitions?.[0]?.competitors||[];const home=g.home_team||g.home?.name||g.homeTeam||comps.find(x=>x.homeAway==='home')?.team?.displayName;const away=g.away_team||g.away?.name||g.awayTeam||comps.find(x=>x.homeAway==='away')?.team?.displayName;const hs=num(g.home_score??g.home_points??g.homeScore??comps.find(x=>x.homeAway==='home')?.score),as=num(g.away_score??g.away_points??g.awayScore??comps.find(x=>x.homeAway==='away')?.score);if(!home||!away||hs==null||as==null)return null;return {home,away,hs,as,date:g.start_time||g.date||g.dateScheduled||g.competitions?.[0]?.date||''}}
function build(games,{initial=4.5,k=.12,homeAdv=.16,formGames=20,decay=.985}={}){const r=new Map(),hist=new Map();const get=t=>r.get(t)||{off:initial,def:initial};const getHist=t=>hist.get(t)||[];const sorted=games.map(parseGame).filter(Boolean).sort((a,b)=>new Date(a.date)-new Date(b.date));for(const g of sorted){const h=key(g.home),a=key(g.away),H=get(h),A=get(a);const expH=Math.max(2.2,H.off-A.def+homeAdv),expA=Math.max(2.2,A.off-H.def);const hResidual=g.hs-expH,aResidual=g.as-expA;const margin=Math.abs(g.hs-g.as);const damp=Math.min(1.35,Math.max(.7,Math.log1p(margin)/1.5));H.off+=k*damp*hResidual;H.def-=k*damp*(g.as-expA);A.off+=k*damp*aResidual;A.def-=k*damp*(g.hs-expH);r.set(h,H);r.set(a,A);for(const [t,pts,opp] of [[h,g.hs,g.as],[a,g.as,g.hs]]){const arr=getHist(t);arr.push({pts,opp});if(arr.length>formGames)arr.shift();hist.set(t,arr)}}return {ratings:r,history:hist,params:{initial,homeAdv,k,formGames,decay},gamesUsed:sorted.length}}
function weighted(a,decay){if(!a.length)return null;let n=0,d=0;for(let i=0;i<a.length;i++){const w=Math.pow(decay,a.length-1-i);n+=a[i]*w;d+=w}return d?n/d:null}
function predictOne(model,home,away){const h=key(home),a=key(away),H=model.ratings.get(h)||{off:4.5,def:4.5},A=model.ratings.get(a)||{off:4.5,def:4.5};const hh=model.history.get(h)||[],aa=model.history.get(a)||[];const havg=weighted(hh.map(x=>x.pts),model.params.decay),aavg=weighted(aa.map(x=>x.pts),model.params.decay);const homeScore=clamp((H.off-A.def+model.params.homeAdv)*.65+(havg??4.5)*.35,2.2,12);const awayScore=clamp((A.off-H.def)*.65+(aavg??4.5)*.35,2.2,12);const total=homeScore+awayScore,margin=homeScore-awayScore,sdMargin=4.0,sdTotal=3.8;return {homeScore,awayScore,total,margin,sdMargin,sdTotal,homeProbability:clamp(normalCdf(0,margin,sdMargin)),awayProbability:clamp(1-normalCdf(0,margin,sdMargin)),gamesUsed:model.gamesUsed}}
function eventPredictions(model,e){const p=predictOne(model,e.home_team||e.home,e.away_team||e.away);return {event_id:e.event_id,source:'MLB_V1',gamesUsed:p.gamesUsed,homeProbability:p.homeProbability,awayProbability:p.awayProbability,expectedHomeScore:p.homeScore,expectedAwayScore:p.awayScore,expectedMargin:p.margin,expectedTotal:p.total,marginSd:p.sdMargin,totalSd:p.sdTotal,features:['recency_weighted_team_run_strength','home_advantage','recent_scoring']}}
function marketProbability(pred,line,kind,side){const n=num(line);if(n==null)return null;if(kind==='runline'||kind==='spread'){const margin=side==='home'?pred.expectedMargin:-pred.expectedMargin;return clamp(normalCdf(-n,margin,pred.marginSd),.01,.99)}if(kind==='total'){return clamp(side==='over'?1-normalCdf(n,pred.expectedTotal,pred.totalSd):normalCdf(n,pred.expectedTotal,pred.totalSd),.01,.99)}return side==='home'?pred.homeProbability:pred.awayProbability}
function predict(model,events){return events.map(e=>eventPredictions(model,e))}
export {build,predict,predictOne,eventPredictions,marketProbability,key};
