import { buildRatings, predict as predictV1 } from './afl-model.js';
import { build as buildV3, predict as predictV3 } from './afl-ml-v2.js';
import { build as buildBasketball, predict as predictBasketball } from './basketball-model.js';

const API_BASE = 'https://api.odds-api.net/v1/odds/main-lines/snapshot';
const AFL_HISTORY_BASE = 'https://api.squiggle.com.au/?q=games;year=';
const ESPN_BASE = 'https://site.api.espn.com/apis/site/v2/sports/basketball/';
const NBL_BASE = 'https://prod.rosetta.nbl.com.au/get/';
const ALLOWED_ORIGINS = new Set(['https://huzzbet.github.io','http://localhost:8788','http://localhost:3000']);
function corsHeaders(request){const origin=request.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://huzzbet.github.io','Access-Control-Allow-Methods':'GET, OPTIONS','Access-Control-Allow-Headers':'Accept, Content-Type','Cache-Control':'no-store','Vary':'Origin'}}
async function fetchAflHistory(){const years=[2024,2025,2026];const rs=await Promise.all(years.map(y=>fetch(`${AFL_HISTORY_BASE}${y}`,{headers:{Accept:'application/json'}})));const ps=await Promise.all(rs.map(r=>r.ok?r.json():{games:[]}));return ps.flatMap(p=>Array.isArray(p.games)?p.games:[])}
async function fetchNblHistory(){const years=[2024,2025,2026];const headers={Accept:'application/json','Origin':'https://nbl.com.au','Referer':'https://nbl.com.au/','User-Agent':'Mozilla/5.0'};const rs=await Promise.all(years.map(y=>fetch(`${NBL_BASE}nbl/matches/in/season/${y}/all`,{headers})));const ps=await Promise.all(rs.map(async r=>r.ok?(await r.json()).data||[]:[]));return ps.flat().map(m=>({event_id:m.id,start_time:m.start_time,home_team:m.home_team?.name||m.home_team,away_team:m.away_team?.name||m.away_team,home_score:m.home_score,away_score:m.away_score}));}
async function fetchBasketballHistory(league){if(league==='NBL')return fetchNblHistory();const seasons=[['20241001','20250630'],['20251001','20260630']];const out=[];for(const [from,to] of seasons){const url=`${ESPN_BASE}nba/scoreboard?dates=${from}-${to}&seasontype=2&limit=1000`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`NBA history source returned ${r.status}`);const body=await r.json();if(Array.isArray(body.events))out.push(...body.events)}return out}
async function attachAflModels(events){try{const history=await fetchAflHistory();const v1=buildRatings(history);const v3=buildV3(history);const p1=predictV1(v1,events);const p3=predictV3(v3,events);const byId=new Map(p3.map(p=>[String(p.event_id),p]));const v1ById=new Map(p1.map(p=>[String(p.event_id),p]));return {events:events.map(e=>{const a=byId.get(String(e.event_id)),b=v1ById.get(String(e.event_id));if(!a)return e;return {...e,model_probabilities:{home:a.homeProbability,away:a.awayProbability},model_source:a.source,model_games_used:a.gamesUsed,model_features:a.features,model_v1_probabilities:b?{home:b.homeProbability,away:b.awayProbability}:null,model_disagreement:b?Math.abs(a.homeProbability-b.homeProbability):null}}),model_meta:{source:'AFL_ML_V3',comparison:'AFL_ELO_V1',history_games:v3.gamesUsed,years:[2024,2025,2026],calibration:'conservative shrinkage in client model layer'}}}catch(error){return {events,model_meta:{source:'UNAVAILABLE',error:error instanceof Error?error.message:String(error)}}}}
async function attachBasketballModels(events,league){try{const history=await fetchBasketballHistory(league);if(!history.length)throw new Error(`${league} historical game feed returned 0 completed games`);const model=buildBasketball(history);const preds=predictBasketball(model,events);const byId=new Map(preds.map(p=>[String(p.event_id),p]));return {events:events.map(e=>{const p=byId.get(String(e.event_id));if(!p)return e;return {...e,model_probabilities:{home:p.homeProbability,away:p.awayProbability},model_expected:{homeScore:p.expectedHomeScore,awayScore:p.expectedAwayScore,margin:p.expectedMargin,total:p.expectedTotal,sd:p.scoreSd},model_source:p.source,model_games_used:p.gamesUsed,model_features:p.features}}),model_meta:{source:'BASKETBALL_V2',league,history_games:model.gamesUsed,history_source:league==='NBL'?'NBL official rosetta/Genius feed':'ESPN scoreboard',markets:['moneyline','spread','total'],status:'paper_validation'}}}catch(error){return {events,model_meta:{source:'UNAVAILABLE',league,error:error instanceof Error?error.message:String(error)}}}}
function normalizeLeague(v){return String(v||'').trim().toUpperCase()}
function filterEvents(events,league){const wanted=normalizeLeague(league),now=Date.now(),horizon=now+120*24*60*60*1000;return (events||[]).filter(e=>{const label=normalizeLeague(e.league||e.sport_league||e.competition||e.sport);if(label!==wanted)return false;const t=new Date(e.start_time||e.commence_time||0).getTime();return Number.isFinite(t)&&t>=now-2*60*60*1000&&t<=horizon})}
export default {async fetch(request,env){const headers=corsHeaders(request);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='GET')return new Response(JSON.stringify({error:'Method not allowed'}),{status:405,headers:{...headers,'Content-Type':'application/json'}});if(!env.ODDS_API_KEY)return new Response(JSON.stringify({error:'ODDS_API_KEY is not configured on the Worker.'}),{status:500,headers:{...headers,'Content-Type':'application/json'}});const incoming=new URL(request.url),league=normalizeLeague(incoming.searchParams.get('league')||'AFL'),bookmakers=incoming.searchParams.get('bookmakers')||'',limit=Math.min(Math.max(Number(incoming.searchParams.get('limit')||25),1),100),upstream=new URL(API_BASE);upstream.searchParams.set('league',league);upstream.searchParams.set('limit',String(limit));if(bookmakers)upstream.searchParams.set('bookmakers',bookmakers);try{const response=await fetch(upstream.toString(),{headers:{'X-API-Key':env.ODDS_API_KEY,Accept:'application/json'}}),body=await response.json();if(!response.ok)return new Response(JSON.stringify(body),{status:response.status,headers:{...headers,'Content-Type':'application/json'}});let events=Array.isArray(body.events)?filterEvents(body.events,league):[];let enriched={...body,events,requested_league:league};if(league==='AFL')enriched={...enriched,...await attachAflModels(events)};if(league==='NBA'||league==='NBL')enriched={...enriched,...await attachBasketballModels(events,league)};return new Response(JSON.stringify(enriched),{status:200,headers:{...headers,'Content-Type':'application/json','X-Edge-IQ-API-Status':String(response.status),'X-Edge-IQ-League':league,'X-Edge-IQ-Model':league==='AFL'?'AFL_ML_V3':(league==='NBA'||league==='NBL'?'BASKETBALL_V2':'NONE')}})}catch(error){return new Response(JSON.stringify({error:'Unable to reach Odds API or model data source.',detail:error instanceof Error?error.message:String(error)}),{status:502,headers:{...headers,'Content-Type':'application/json'}})}}};
