import { buildRatings, predict as predictV1 } from './afl-model.js';
import { build as buildV2, predict as predictV2 } from './afl-ml-v2.js';

const API_BASE = 'https://api.odds-api.net/v1/odds/main-lines/snapshot';
const AFL_HISTORY_BASE = 'https://api.squiggle.com.au/?q=games;year=';
const ALLOWED_ORIGINS = new Set(['https://huzzbet.github.io','http://localhost:8788','http://localhost:3000']);
function corsHeaders(request){const origin=request.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://huzzbet.github.io','Access-Control-Allow-Methods':'GET, OPTIONS','Access-Control-Allow-Headers':'Accept, Content-Type','Cache-Control':'no-store','Vary':'Origin'}}
async function fetchAflHistory(){const years=[2024,2025,2026];const rs=await Promise.all(years.map(y=>fetch(`${AFL_HISTORY_BASE}${y}`,{headers:{Accept:'application/json'}})));const ps=await Promise.all(rs.map(r=>r.ok?r.json():{games:[]}));return ps.flatMap(p=>Array.isArray(p.games)?p.games:[])}
async function attachAflModels(events){try{const history=await fetchAflHistory();const v1=buildRatings(history);const v2=buildV2(history);const p1=predictV1(v1,events);const p2=predictV2(v2,events);const byId=new Map(p2.map(p=>[String(p.event_id),p]));const v1ById=new Map(p1.map(p=>[String(p.event_id),p]));return {events:events.map(e=>{const a=byId.get(String(e.event_id)),b=v1ById.get(String(e.event_id));if(!a)return e;return {...e,model_probabilities:{home:a.homeProbability,away:a.awayProbability},model_source:a.source,model_games_used:a.gamesUsed,model_features:a.features,model_v1_probabilities:b?{home:b.homeProbability,away:b.awayProbability}:null,model_disagreement:b?Math.abs(a.homeProbability-b.homeProbability):null}}),model_meta:{source:'AFL_ML_V2',comparison:'AFL_ELO_V1',history_games:v2.gamesUsed,years:[2024,2025,2026]}}}catch(error){return {events,model_meta:{source:'UNAVAILABLE',error:error instanceof Error?error.message:String(error)}}}}
function normalizeLeague(v){return String(v||'').trim().toUpperCase()}
function filterEvents(events,league){const wanted=normalizeLeague(league);return (events||[]).filter(e=>normalizeLeague(e.league||e.sport_league||e.competition||e.sport)===wanted)}
export default {async fetch(request,env){const headers=corsHeaders(request);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='GET')return new Response(JSON.stringify({error:'Method not allowed'}),{status:405,headers:{...headers,'Content-Type':'application/json'}});if(!env.ODDS_API_KEY)return new Response(JSON.stringify({error:'ODDS_API_KEY is not configured on the Worker.'}),{status:500,headers:{...headers,'Content-Type':'application/json'}});const incoming=new URL(request.url),league=normalizeLeague(incoming.searchParams.get('league')||'AFL'),bookmakers=incoming.searchParams.get('bookmakers')||'',limit=Math.min(Math.max(Number(incoming.searchParams.get('limit')||25),1),100),upstream=new URL(API_BASE);upstream.searchParams.set('league',league);upstream.searchParams.set('limit',String(limit));if(bookmakers)upstream.searchParams.set('bookmakers',bookmakers);try{const response=await fetch(upstream.toString(),{headers:{'X-API-Key':env.ODDS_API_KEY,Accept:'application/json'}}),body=await response.json();if(!response.ok)return new Response(JSON.stringify(body),{status:response.status,headers:{...headers,'Content-Type':'application/json'}});let events=Array.isArray(body.events)?filterEvents(body.events,league):[];let enriched={...body,events,requested_league:league};if(league==='AFL')enriched={...enriched,...await attachAflModels(events)};return new Response(JSON.stringify(enriched),{status:200,headers:{...headers,'Content-Type':'application/json','X-Edge-IQ-API-Status':String(response.status),'X-Edge-IQ-League':league}})}catch(error){return new Response(JSON.stringify({error:'Unable to reach Odds API or AFL model data source.',detail:error instanceof Error?error.message:String(error)}),{status:502,headers:{...headers,'Content-Type':'application/json'}})}}};
